# Default values for kimestry.

# External PostgreSQL database configuration
database:
  host: "your-postgres-host"
  port: 5432
  database: "kimestry"
  username: "postgres"
  password: "your-password"
  sslMode: "prefer"  # Options: disable, allow, prefer, require, verify-ca, verify-full

# Backend API configuration
backend:
  replicaCount: 1
  image:
    repository: kimestry-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    port: 8000
    postgres_connection_string: "postgresql://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.database }}?sslmode={{ .Values.database.sslMode }}"

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: kimestry-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Nginx configuration for frontend
nginx:
  enabled: true

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kimestry.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Persistence configuration
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce