# Default values for kimestry-benchmark Helm chart

# Backend API configuration
backend:
  replicaCount: 1
  image:
    repository: kimestry-benchmark-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: kimestry-benchmark-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kimestry-benchmark.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Database configuration - expects a secret with connection string
database:
  secretName: kimestry-db-secret