apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kimestry-benchmark.backend.fullname" . }}
  labels:
    {{- include "kimestry-benchmark.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "kimestry-benchmark.selectorLabels" . | nindent 6 }}
      app: kimestry-benchmark-backend
  template:
    metadata:
      labels:
        {{- include "kimestry-benchmark.selectorLabels" . | nindent 8 }}
        app: kimestry-benchmark-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.backend.service.port }}"
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | default "kimestry-db-secret" }}
                  key: connection-string
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kimestry-benchmark.backend.fullname" . }}
  labels:
    {{- include "kimestry-benchmark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: kimestry-benchmark-backend