apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kimestry.backend.fullname" . }}
  labels:
    {{- include "kimestry.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "kimestry.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kimestry.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.backend.env.port }}"
            - name: POSTGRES_CONNECTION_STRING
              value: {{ .Values.backend.env.postgres_connection_string | quote }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kimestry.backend.fullname" . }}
  labels:
    {{- include "kimestry.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kimestry.backend.selectorLabels" . | nindent 4 }}